# -*- coding: utf-8 -*-
"""Assignment-Pedram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177iFz6wHHGbMQ4fietaXgMgPi8IAAkR_

# Demand Forecasting Problem:

## Import the libraries:
"""

import numpy as np
import matplotlib.pyplot as plt ## using module pyplot from the library matplotlib
import pandas as pd

"""## Import the datasets:"""

# Reading the data files
locations = pd.read_csv('locations.csv')  # assuming tab-delimited or adjust accordingly
products = pd.read_csv('products.csv')
transactions = pd.read_csv('transactions.csv')

print(locations.info())
print(locations.head())
print("---------------------------------------------------")
print(products.info())
print(products.head())
print("---------------------------------------------------")
print(transactions.info())
print(transactions.head())

"""## Exploratory Data Analysis (EDA) Steps:

### Standardization of Data Type:
"""

# Data Standardization
## locations
locations['Location ID'] = locations['Location ID'].astype(int)
locations['Province'] = locations['Province'].str.strip().str.upper()
locations['Region Type'] = locations['Region Type'].str.strip().str.title()
locations['Surface Area'] = locations['Surface Area'].str.replace(',', '').astype(float)
Duplicates_locations = locations.duplicated(subset=['Location ID']).sum()
if Duplicates_locations > 0:
    print(f"Found {Duplicates_locations} duplicate Location IDs. Dropping duplicates.")
    locations.drop_duplicates(subset=['Location ID'], inplace=True)
#print(locations.describe())
print("locations:\n", locations)

## products
products['SKU'] = products['SKU'].str.strip().str.title()
products['Product Class'] = products['Product Class'].str.strip().str.upper()
products['Product Family'] = products['Product Family'].str.strip()
products['MSRP ($)'] = products['MSRP ($)'].astype(float)
products['Margin (%)'] = products['Margin (%)'].astype(float)
Duplicates_products = products.duplicated(subset=['SKU']).sum()
if Duplicates_products > 0:
    print(f"Found {Duplicates_products} duplicate SKU. Dropping duplicates.")
    products.drop_duplicates(subset=['SKU'], inplace=True)
print("products:\n", products)

## transactions
transactions['Date'] = pd.to_datetime(transactions['Date'], errors='coerce')
transactions['Location ID'] = pd.to_numeric(transactions['Location ID'], errors='coerce').astype('Int64')
transactions['SKU'] = transactions['SKU'].str.strip().str.title()
transactions['Quantity'] = transactions['Quantity'].astype(int)
transactions['Value ($)'] = transactions['Value ($)'].astype(int)
Duplicates_Transactions = transactions.duplicated(subset=['Transaction ID']).sum()
if Duplicates_Transactions > 0:
    print(f"Found {Duplicates_Transactions} duplicate Transaction ID. Dropping duplicates.")
    transactions.drop_duplicates(subset=['Transaction ID'], inplace=True)
print("transactions:\n", transactions)

"""### Missing Data:"""

## Finding out the missing data:

print(locations.isnull().sum())
print(products.isnull().sum())
print(transactions.isnull().sum())


## Start working on missing data
locations['Surface Area'] = (locations.groupby('Region Type')['Surface Area'].transform(lambda x: x.fillna(x.mean())))

# Make sure ther is no missing data left
print("----------------- After Mean replacement:")
print(locations.isnull().sum())

"""### Descriptive Statistics with Visualizations:"""

print(transactions.describe())

negative_qty_mask = transactions['Quantity'] < 0
if negative_qty_mask.any():
    # Option 1: Use the absolute value if negatives are data errors.
    transactions.loc[negative_qty_mask, 'Quantity'] = transactions.loc[negative_qty_mask, 'Quantity'].abs()
    print("Negative quantities found and converted to their absolute values.")

    # Option 2: Alternatively, if negatives should not be present at all, you could drop those rows:
    # transactions = transactions[transactions['Quantity'] >= 0]
else:
    print("No negative quantities found.")
print(transactions.describe())

# ----- 2. Validate the "Value ($)" Column -----

# Merge transactions with products on the 'SKU' column to fetch the MSRP value for each product.
merged = transactions.merge(products[['SKU', 'MSRP ($)']], on='SKU', how='left')

# Calculate the expected transaction value using the formula: Quantity * MSRP($)
merged['Expected Value'] = merged['Quantity'] * merged['MSRP ($)']
print("merged: \n", merged)
# Compare the computed Expected Value with the recorded Value ($)
mismatches = merged[merged['Value ($)'] != merged['Expected Value']]

if not mismatches.empty:
    print("Found discrepancies between recorded Value ($) and expected value computed as Quantity * MSRP ($).")
    print(mismatches[['Transaction ID', 'SKU', 'Quantity', 'MSRP ($)', 'Value ($)', 'Expected Value']])
else:
    print("All transaction values are consistent with Quantity * MSRP ($) as expected.")

print(transactions.describe())

# Histogram of Quantity
transactions['Quantity'].hist(bins=20)
plt.xlabel('Quantity')
plt.ylabel('Frequency')
plt.title('Distribution of Transaction Quantity')
plt.show()

# Boxplot of Value ($)
plt.figure(figsize=(8,6))
transactions.boxplot(column='Value ($)')
plt.title('Boxplot of Transaction Value')
plt.show()

# Trend Analysis: Aggregate daily sales
daily_sales = transactions.groupby('Date')['Quantity'].sum()
daily_sales.plot(figsize=(10, 5), title='Daily Quantity Sold')
plt.xlabel('Date')
plt.ylabel('Total Quantity')
plt.show()